### ISSUE TITLE
Problem using grunt-static-inline

### ISSUE THREAD

**Issue by XhmikosR** [dayvson/grunt-static-inline#13]
Hey, there.

I was trying to use grunt-static-inline in one of my projects.

I'm using node.js 0.12.7 on Windows 7.

```html
<script src="/assets/js/downloads.js" inline="true"></script>
```

```js
staticinline: {
    dist: {
        files: [{
          expand: true,
          cwd: "<%= dirs.dest %>/",
          src: "**/*.{html,php}",
          dest: "<%= dirs.dest %>/"
        }]
    }
}
```

```
Running "staticinline:main" (staticinline) task
Warning: Unable to read "C:\assets\js\downloads.js" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.
```

`<%= dirs.dest %>` is relative to gruntfile.js, and the files are there.

I tried to dig into the source, but couldn't make it to work. Note that all the tests pass on Windows so something else is wrong.

Thanks in advance!

EDIT: Here is a temp branch  https://github.com/mpc-hc/mpc-hc.org/tree/downloads-2

**Comment by XhmikosR** [comment]
The problem is on Windows. Here is a branch with the temp fix  https://github.com/dayvson/grunt-static-inline/compare/master...mpc-hc:custom?w=1

**Comment by dayvson** [comment]
Thanks for that! Please send a pull request when you have a final solution and I will merge it

**Comment by XhmikosR** [comment]
@dayvson: have you reviewed that branch? It would save me a lot of time if I could just make a PR with all the changes apart from the last one.
