### ISSUE TITLE
Multiple files are not handled correctly

### ISSUE THREAD

**Issue by sinelaw** [dayvson/grunt-static-inline#9]
If the 'files' option is set in the File Object Format (http://gruntjs.com/configuring-tasks#files-object-format), grunt-static-inline handles the input incorrectly.

Example:

	files: [
		{
			expand: true,
			dot: true,
			cwd: 'srcDir',
			dest: 'dstDir',
			src: [
				'**/*.html',
				'!test/**/*.html'
			]
		}
	]

Results in an error:

    Warning: Unable to read "**/*.html" file (Error code: ENOENT). Use --force to continue.

**Comment by XhmikosR** [comment]
This seems to have been fixed in https://github.com/dayvson/grunt-static-inline/pull/10

**Comment by XhmikosR** [comment]
@dayvson: you can close this too I think, see the previous comment.
